"""create user click history table

Revision ID: f251e5ad0d46
Revises: 82244b89905e
Create Date: 2025-10-08 17:52:19.270368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f251e5ad0d46'
down_revision: Union[str, Sequence[str], None] = '82244b89905e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_click_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('artifact_id', sa.String(length=8), nullable=False),
    sa.Column('clicked_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_artifact_clicked', 'user_click_history', ['user_id', 'artifact_id', 'clicked_at'], unique=False)
    op.create_index(op.f('ix_user_click_history_artifact_id'), 'user_click_history', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_user_click_history_user_id'), 'user_click_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_click_history_user_id'), table_name='user_click_history')
    op.drop_index(op.f('ix_user_click_history_artifact_id'), table_name='user_click_history')
    op.drop_index('idx_user_artifact_clicked', table_name='user_click_history')
    op.drop_table('user_click_history')
    # ### end Alembic commands ###
